-   id: zig_fmt
    name: ziglang
    description: 'format zig'
    entry: python -m ziglang fmt
    language: python
    'types': [zig]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
